-- ============================================================================
--  Schema kho dữ liệu HỎI - ĐÁP PHÁP LUẬT  (PostgreSQL)
--  Thiết kế dạng "sao": bảng sự kiện cau_hoi + các bảng chiều nguon / chu_de /
--  van_ban, và 2 bảng nối (cau_hoi_van_ban, trich_dan).
--  Chạy 1 lần trên DB rỗng (vd DB "questions", schema public).
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;   -- tìm kiếm gần đúng (ILIKE nhanh)

-- ---------------------------------------------------------------------------
-- 1) NGUỒN  — mỗi trang/nguồn dữ liệu
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS nguon (
    nguon_id  smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma        text UNIQUE NOT NULL,        -- 'plo', 'chinhsachonline'
    ten       text NOT NULL,               -- tên đầy đủ
    website   text
);

-- ---------------------------------------------------------------------------
-- 2) CHỦ ĐỀ  — lĩnh vực/chủ đề (Giao thông, Đất đai, Lao động - BHXH, ...)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chu_de (
    chu_de_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten       text UNIQUE NOT NULL
);

-- ---------------------------------------------------------------------------
-- 3) VĂN BẢN PHÁP LUẬT  — mỗi văn bản CHỈ lưu 1 lần, gộp trùng theo `khoa`
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS van_ban (
    van_ban_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    khoa       text UNIQUE NOT NULL,       -- khóa gộp trùng: số hiệu chuẩn hóa, else tên chuẩn hóa
    so_hieu    text,                       -- '168/2024/NĐ-CP' (NULL nếu chỉ có tên)
    ten        text NOT NULL,              -- tên như được trích dẫn
    loai       text,                       -- 'Luật','Bộ luật','Nghị định','Thông tư',...
    link       text                        -- link văn bản gốc (nếu nguồn cung cấp)
);

-- ---------------------------------------------------------------------------
-- 4) CÂU HỎI - ĐÁP  (bảng sự kiện chính)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cau_hoi (
    cau_hoi_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguon_id     smallint NOT NULL REFERENCES nguon(nguon_id),
    chu_de_id    smallint REFERENCES chu_de(chu_de_id),
    chuyen_muc   text,                     -- chuyên mục gốc trong nguồn ("Tôi muốn hỏi"...)
    tieu_de      text NOT NULL,
    cau_hoi      text,
    dap_an       text,
    ngay_dang    timestamp,                -- đã parse
    ngay_text    text,                     -- chuỗi ngày gốc
    url          text,
    content_hash text UNIQUE NOT NULL,     -- md5(nguon|tieu_de|cau_hoi) -> nạp lại không trùng
    raw          jsonb,                    -- bản ghi gốc (dự phòng, khai thác linh hoạt)
    created_at   timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 5) CÂU HỎI ↔ VĂN BẢN  (mức văn bản — từ "van_ban_dan_chieu")
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cau_hoi_van_ban (
    cau_hoi_id bigint NOT NULL REFERENCES cau_hoi(cau_hoi_id) ON DELETE CASCADE,
    van_ban_id bigint NOT NULL REFERENCES van_ban(van_ban_id),
    PRIMARY KEY (cau_hoi_id, van_ban_id)
);

-- ---------------------------------------------------------------------------
-- 6) TRÍCH DẪN  (mức điều/khoản/điểm — từ "trich_dan")
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trich_dan (
    trich_dan_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cau_hoi_id    bigint NOT NULL REFERENCES cau_hoi(cau_hoi_id) ON DELETE CASCADE,
    van_ban_id    bigint REFERENCES van_ban(van_ban_id),
    dieu          text,
    khoan         text,
    diem          text,
    trich_dan_goc text,
    link          text
);

-- ---------------------------------------------------------------------------
-- Chỉ mục phục vụ khai thác
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS ix_cauhoi_nguon    ON cau_hoi(nguon_id);
CREATE INDEX IF NOT EXISTS ix_cauhoi_chude    ON cau_hoi(chu_de_id);
CREATE INDEX IF NOT EXISTS ix_cauhoi_ngay     ON cau_hoi(ngay_dang);
CREATE INDEX IF NOT EXISTS ix_cauhoi_tieude_trgm ON cau_hoi USING gin (tieu_de gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_cauhoi_cauhoi_trgm ON cau_hoi USING gin (cau_hoi gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_chvb_vanban     ON cau_hoi_van_ban(van_ban_id);
CREATE INDEX IF NOT EXISTS ix_trichdan_cauhoi ON trich_dan(cau_hoi_id);
CREATE INDEX IF NOT EXISTS ix_trichdan_vanban ON trich_dan(van_ban_id);
CREATE INDEX IF NOT EXISTS ix_trichdan_dieu   ON trich_dan(van_ban_id, dieu, khoan);

-- ---------------------------------------------------------------------------
-- View tiện tra cứu
-- ---------------------------------------------------------------------------
-- Câu hỏi kèm nguồn + chủ đề (phẳng)
CREATE OR REPLACE VIEW v_cau_hoi AS
SELECT c.cau_hoi_id, n.ten AS nguon, c.chuyen_muc, d.ten AS chu_de,
       c.ngay_dang, c.tieu_de, c.cau_hoi, c.dap_an, c.url
FROM cau_hoi c
JOIN nguon n  ON n.nguon_id = c.nguon_id
LEFT JOIN chu_de d ON d.chu_de_id = c.chu_de_id;

-- Trích dẫn phẳng (câu hỏi × điều/khoản × văn bản)
CREATE OR REPLACE VIEW v_trich_dan AS
SELECT t.trich_dan_id, c.cau_hoi_id, d.ten AS chu_de, c.tieu_de,
       v.so_hieu, v.ten AS van_ban, v.loai,
       t.dieu, t.khoan, t.diem, t.trich_dan_goc, t.link
FROM trich_dan t
JOIN cau_hoi c ON c.cau_hoi_id = t.cau_hoi_id
LEFT JOIN chu_de d ON d.chu_de_id = c.chu_de_id
LEFT JOIN van_ban v ON v.van_ban_id = t.van_ban_id;

-- Xếp hạng văn bản được trích dẫn nhiều nhất
CREATE OR REPLACE VIEW v_van_ban_pho_bien AS
SELECT v.van_ban_id, v.so_hieu, v.ten, v.loai,
       count(*) AS so_luot_trich_dan,
       count(DISTINCT t.cau_hoi_id) AS so_cau_hoi
FROM trich_dan t JOIN van_ban v ON v.van_ban_id = t.van_ban_id
GROUP BY v.van_ban_id, v.so_hieu, v.ten, v.loai
ORDER BY so_luot_trich_dan DESC;




DELETE FROM cau_hoi WHERE cau_hoi_id = 11;