-- ============================================================================
--  Bổ sung schema: bảng DANH MỤC trong văn bản pháp luật
--  Chạy SAU schema.sql, trên cùng DB "questions" (cần bảng van_ban đã có).
--
--  Một bảng duy nhất cho mọi danh mục: cột chung + `thuoc_tinh` (jsonb) cho
--  phần riêng của từng danh mục. Nhờ vậy thêm danh mục mới (bí mật nhà nước,
--  ngành nghề kinh doanh có điều kiện, phế liệu...) không phải ALTER TABLE.
-- ============================================================================

CREATE TABLE IF NOT EXISTS danh_muc (
    danh_muc_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_danh_muc  text NOT NULL,         -- 'nghe_nndhnh' | 'hoa_chat_nd24'
    ten_danh_muc text NOT NULL,         -- tên đầy đủ của danh mục
    van_ban_id   bigint REFERENCES van_ban(van_ban_id),
    so_hieu      text,                  -- '11/2020/TT-BLĐTBXH' (tiện lọc, khỏi join)
    phan_muc     text,                  -- lĩnh vực | phụ lục + mục
    nhom_cha     text,                  -- 'Loại IV' | 'A. Các tiền chất công nghiệp'
    nhom_con     text,                  -- phân loại nghề | '2B. Các tiền chất'
    stt          text,                  -- STT trong văn bản (KHÔNG duy nhất)
    ten          text NOT NULL,         -- tên nghề | tên chất tiếng Việt
    ten_khac     text,                  -- tên khoa học IUPAC / tiếng Anh
    ma           text[],                -- mã định danh: CAS (sau này có thể là mã HS)
    mo_ta        text,                  -- đặc điểm điều kiện lao động...
    thuoc_tinh   jsonb NOT NULL DEFAULT '{}',
    content_hash text UNIQUE NOT NULL,  -- nạp lại không nhân bản
    created_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_danhmuc_ma_danh_muc ON danh_muc(ma_danh_muc);
CREATE INDEX IF NOT EXISTS ix_danhmuc_vanban      ON danh_muc(van_ban_id);
CREATE INDEX IF NOT EXISTS ix_danhmuc_phanmuc     ON danh_muc(ma_danh_muc, phan_muc);
CREATE INDEX IF NOT EXISTS ix_danhmuc_ma          ON danh_muc USING gin (ma);
CREATE INDEX IF NOT EXISTS ix_danhmuc_thuoctinh   ON danh_muc USING gin (thuoc_tinh);
CREATE INDEX IF NOT EXISTS ix_danhmuc_ten_trgm    ON danh_muc USING gin (ten gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_danhmuc_tenkhac_trgm
    ON danh_muc USING gin (ten_khac gin_trgm_ops);

-- Danh mục kèm văn bản ban hành (phẳng, tiện tra cứu)
CREATE OR REPLACE VIEW v_danh_muc AS
SELECT d.danh_muc_id, d.ma_danh_muc, d.ten_danh_muc,
       coalesce(v.so_hieu, d.so_hieu) AS so_hieu, v.ten AS van_ban, v.loai,
       d.phan_muc, d.nhom_cha, d.nhom_con, d.stt,
       d.ten, d.ten_khac, d.ma, d.mo_ta, d.thuoc_tinh
FROM danh_muc d
LEFT JOIN van_ban v ON v.van_ban_id = d.van_ban_id;

-- Câu hỏi test ↔ danh mục, nối qua văn bản được trích dẫn.
-- Đây là mục đích chính của việc nạp danh mục vào cùng DB với cau_hoi:
-- biết một câu hỏi dựa trên văn bản nào thì tra ngay được danh mục của văn bản đó.
CREATE OR REPLACE VIEW v_cau_hoi_danh_muc AS
SELECT c.cau_hoi_id, c.tieu_de, v.so_hieu, v.ten AS van_ban,
       d.ma_danh_muc, count(*) AS so_muc
FROM cau_hoi c
JOIN cau_hoi_van_ban cv ON cv.cau_hoi_id = c.cau_hoi_id
JOIN van_ban v          ON v.van_ban_id = cv.van_ban_id
JOIN danh_muc d         ON d.van_ban_id = v.van_ban_id
GROUP BY c.cau_hoi_id, c.tieu_de, v.so_hieu, v.ten, d.ma_danh_muc;
