-- ============================================================================
--  DANH MỤC trong văn bản pháp luật — 2 bảng, phân cấp bằng MẢNG ĐƯỜNG DẪN
--  Chạy trên DB "questions" (schema public). Thay cho bản dùng 3 cột cố định
--  phan_muc / nhom / nhom_con (đã bỏ).
--
--  Vì sao đổi: bản gốc hai văn bản có số tầng khác nhau —
--    nghề     2 tầng   lĩnh vực → loại điều kiện lao động
--    hóa chất 4 tầng   Phụ lục → Mục → Nhóm A/B/C → Nhóm con
--  Ba cột cố định vì thế vừa thiếu (phải nối 'Phụ lục III - 1.1. Nhóm 1' vào
--  một chuỗi) vừa thừa (nhom_con NULL suốt 2.429 dòng nghề).
--
--   danh_muc              2 dòng — tên, mô tả, văn bản, NHÃN từng tầng
--        └──< danh_muc_chi_tiet — từng nghề / từng hóa chất
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------------------
-- 1) DANH MỤC
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS danh_muc (
    danh_muc_id    smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma             text UNIQUE NOT NULL,   -- 'nghe_nndhnh' | 'hoa_chat'
    ten            text NOT NULL,
    ten_ngan       text,
    linh_vuc       text,
    co_quan        text,
    can_cu         text,                   -- luật gốc mà danh mục chi tiết hóa
    van_ban        text[],                 -- tên các văn bản của danh mục này
    mo_ta          text,
    dung_de_lam_gi text,
    pham_vi        text,
    luu_y          text,

    -- Nhãn cho các cột dùng chung ở bảng chi tiết. `nhan_cap` khai nghĩa TỪNG
    -- TẦNG của duong_dan, ghép theo chỉ số: nhan_cap[i] ứng với duong_dan[i].
    --   nghề     {'Lĩnh vực', 'Điều kiện lao động'}
    --   hóa chất {'Phụ lục', 'Mục', 'Nhóm', 'Nhóm con'}
    nhan_cap       text[],
    nhan_ten       text,                   -- 'Tên nghề, công việc' | 'Tên chất'
    -- Nhãn dùng cho dòng có loai_muc='nhom'. Cần cột riêng vì trong CÙNG một
    -- văn bản, chủ thể của bảng có thể đổi: Phụ lục IV Bảng A liệt kê từng
    -- chất (tiêu đề 'Tên chất'), Bảng B liệt kê nhóm nguy hại (tiêu đề
    -- 'Nhóm hóa chất'). Một nhãn cho cả danh mục thì 21 dòng Bảng B bị gắn
    -- sai là 'Tên chất'.
    nhan_ten_nhom  text,                   -- NULL | 'Nhóm hóa chất'
    nhan_ten_khac  text,                   -- NULL | 'Tên khoa học (IUPAC)'
    nhan_ma        text,                   -- NULL | 'Mã số CAS'
    nhan_mo_ta     text,                   -- 'Đặc điểm điều kiện lao động' | NULL

    -- so_muc chỉ đếm mục THẬT (loai_muc='muc' tính ở v_danh_muc_chi_tiet);
    -- so_dong đếm tất cả, kể cả dòng nhóm / ghi chú / nối tiếp. Trước đây chỉ
    -- có một số đếm nên nó nói QUÁ số hóa chất thật (1.376 thay vì 1.348).
    -- Cả hai do script nạp cập nhật.
    so_muc         integer,
    so_dong        integer,
    cap_nhat_luc   timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2) CHI TIẾT — 10 cột, không cột nào rỗng vì "tầng này danh mục kia không dùng"
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS danh_muc_chi_tiet (
    muc_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    danh_muc_id  smallint NOT NULL
                 REFERENCES danh_muc(danh_muc_id) ON DELETE CASCADE,
    -- Văn bản ban hành mục này. Hai cột đi CẶP:
    --   van_ban      tên đọc được, 1 trong danh_muc.van_ban   -> để nhìn
    --   van_ban_id   khóa ngoại sang bảng `van_ban` của DB     -> để JOIN
    -- Bảng `van_ban` đã có sẵn trong DB questions (2.612 dòng, có `link`) và
    -- bộ câu hỏi test nối vào nó qua `cau_hoi_van_ban`. Không có cột id này thì
    -- không join được câu hỏi test với danh mục dùng để chấm nó — mà đó là lý
    -- do bộ danh mục nằm trong DB này.
    -- Tra id theo `khoa` (cột UNIQUE) chứ KHÔNG theo `so_hieu`: so_hieu NULL ở
    -- 732/2.612 dòng và không có ràng buộc duy nhất.
    van_ban      text,
    van_ban_id   bigint REFERENCES van_ban(van_ban_id),

    -- Đường dẫn phân cấp, sâu bao nhiêu tầng cũng được:
    --   {'XV. Y TẾ VÀ DƯỢC', 'Loại V'}
    --   {'Phụ lục III', '1.1. Nhóm 1', 'A. CÁC TIỀN CHẤT CÔNG NGHIỆP', 'Nhóm 1 (IVB)…'}
    duong_dan    text[] NOT NULL,

    stt          text,          -- STT trong văn bản — KHÔNG duy nhất
    ten          text NOT NULL, -- tên nghề | tên chất | nhóm nguy hại
    ten_khac     text,          -- tên khoa học IUPAC / tiếng Anh
    -- Mã CAS. Để `text` chứ không phải text[] cho đọc bằng mắt khỏi thấy dấu
    -- {} của kiểu mảng. 17 chất có nhiều mã, ngăn bởi '; ' — tra chính xác thì
    -- dùng  '71-43-2' = ANY(string_to_array(ma_cas, '; '))
    ma_cas       text,

    -- hai cột riêng của hóa chất, lấy nguyên từ cột cùng tên trong văn bản
    cong_thuc_hoa_hoc    text,
    nguong_khoi_luong_kg text,  -- chỉ Phụ lục IV có; giữ nguyên văn '5.000'

    mo_ta        text,          -- đặc điểm điều kiện lao động…

    content_hash text UNIQUE NOT NULL,
    created_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_ct_danh_muc  ON danh_muc_chi_tiet(danh_muc_id);
CREATE INDEX IF NOT EXISTS ix_ct_van_ban   ON danh_muc_chi_tiet(danh_muc_id, van_ban);
CREATE INDEX IF NOT EXISTS ix_ct_van_ban_id ON danh_muc_chi_tiet(van_ban_id);
CREATE INDEX IF NOT EXISTS ix_ct_duong_dan ON danh_muc_chi_tiet USING gin (duong_dan);
CREATE INDEX IF NOT EXISTS ix_ct_cap1      ON danh_muc_chi_tiet (danh_muc_id, (duong_dan[1]));
CREATE INDEX IF NOT EXISTS ix_ct_macas     ON danh_muc_chi_tiet USING gin (ma_cas gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_ct_ten_trgm  ON danh_muc_chi_tiet USING gin (ten gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ix_ct_tenkh_trgm
    ON danh_muc_chi_tiet USING gin (ten_khac gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- View tra cứu chính. `vi_tri` là đường dẫn đã nối để đọc bằng mắt;
-- `phan_loai_nghe` tính tại chỗ từ duong_dan chứ không lưu.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_danh_muc_chi_tiet AS
SELECT ct.muc_id,
       dm.ma        AS ma_danh_muc,
       dm.ten_ngan,
       ct.van_ban,
       ct.van_ban_id,
       vb.ten  AS ten_van_ban,     -- tên đầy đủ, lấy từ bảng van_ban
       vb.link AS link_van_ban,    -- nguồn để đối chiếu nguyên văn
       ct.duong_dan,
       array_to_string(ct.duong_dan, ' › ') AS vi_tri,
       ct.duong_dan[1] AS cap_1,
       ct.duong_dan[2] AS cap_2,
       -- Dòng này là gì. TÍNH TẠI CHỖ, không lưu cột, vì suy được 100% từ dữ
       -- liệu sẵn có. Bản gốc trộn 4 kiểu dòng vào cùng một bảng:
       --   'muc'       mục thật của danh mục — một nghề, một chất
       --   'nhom'      một NHÓM chứ không phải cá thể. Dấu hiệu CẤU TRÚC:
       --               Phụ lục IV Bảng B có cột 'Nhóm hóa chất' thay cho cột
       --               'Tên chất', nên không có mã CAS lẫn công thức.
       --   'tiep_noi'  nửa sau của một mục bị xuống dòng. Dấu hiệu: tên Việt
       --               mở đầu 'và ', tên Anh mở đầu 'and '. Đã kiểm ngược: 0
       --               chất có CAS hoặc công thức mà tên mở đầu như vậy.
       --               KHÔNG dùng luật "bắt đầu bằng chữ thường" — 34 dòng
       --               khớp nhưng phần lớn là chất thật (n-Butanol, o-Anisidin).
       --   'ghi_chu'   lời dẫn: 'Ví dụ', 'Ngoại trừ: Fonofos:'
       -- Cả 4 kiểu đều là hàng riêng THẬT trong văn bản (Word còn đánh số cho
       -- chúng) nên đều lưu nguyên; phân loại chỉ để đếm và gắn nhãn cho đúng.
       CASE
         WHEN ct.ten ~* '^(và|and)\s'
           OR ct.ten_khac ~* '^(và|and)\s'          THEN 'tiep_noi'
         WHEN ct.ten ~ '^(Ví dụ|Ngoại trừ)\M'       THEN 'ghi_chu'
         WHEN ct.duong_dan[2] LIKE '%Bảng B%'
           AND ct.ma_cas IS NULL
           AND ct.cong_thuc_hoa_hoc IS NULL         THEN 'nhom'
         ELSE 'muc'
       END AS loai_muc,
       ct.stt, ct.ten, ct.ten_khac, ct.ma_cas,
       -- nhãn ĐÚNG cho cột `ten` của chính dòng này
       CASE WHEN ct.duong_dan[2] LIKE '%Bảng B%'
                 AND ct.ma_cas IS NULL AND ct.cong_thuc_hoa_hoc IS NULL
            THEN coalesce(dm.nhan_ten_nhom, dm.nhan_ten)
            ELSE dm.nhan_ten END AS nhan_ten,
       ct.cong_thuc_hoa_hoc, ct.nguong_khoi_luong_kg, ct.mo_ta,
       CASE WHEN ct.duong_dan && ARRAY['Loại V','Loại VI']
                 THEN 'Đặc biệt nặng nhọc, độc hại, nguy hiểm'
            WHEN 'Loại IV' = ANY(ct.duong_dan)
                 THEN 'Nặng nhọc, độc hại, nguy hiểm'
       END AS phan_loai_nghe
FROM danh_muc_chi_tiet ct
JOIN danh_muc dm ON dm.danh_muc_id = ct.danh_muc_id
LEFT JOIN van_ban vb ON vb.van_ban_id = ct.van_ban_id;

-- Từng tầng của đường dẫn kèm ĐÚNG nhãn của nó — đây là chỗ thấy rõ vì sao
-- nhãn phải nằm ở bảng cha: tầng 2 của nghề là mức độ nặng nhọc, tầng 2 của
-- hóa chất là mục trong phụ lục.
CREATE OR REPLACE VIEW v_danh_muc_tang AS
SELECT ct.muc_id, dm.ma AS ma_danh_muc, ct.ten,
       i AS cap, dm.nhan_cap[i] AS nhan, ct.duong_dan[i] AS gia_tri
FROM danh_muc_chi_tiet ct
JOIN danh_muc dm ON dm.danh_muc_id = ct.danh_muc_id,
     generate_subscripts(ct.duong_dan, 1) i;

-- Kiểm tra chéo thay cho ràng buộc DB: cột `van_ban` ở bảng chi tiết không được
-- khóa ngoại kiểm. Có dòng nào trả về là sai dữ liệu.
CREATE OR REPLACE VIEW v_danh_muc_sai_van_ban AS
SELECT dm.ma, ct.van_ban, count(*) AS so_dong
FROM danh_muc_chi_tiet ct
JOIN danh_muc dm ON dm.danh_muc_id = ct.danh_muc_id
WHERE ct.van_ban IS NOT NULL AND NOT (ct.van_ban = ANY(dm.van_ban))
GROUP BY 1, 2;

-- Đường dẫn sâu hơn số nhãn đã khai ở bảng cha -> thiếu nhãn, cũng là lỗi.
CREATE OR REPLACE VIEW v_danh_muc_thieu_nhan AS
SELECT dm.ma, array_length(ct.duong_dan, 1) AS so_tang,
       array_length(dm.nhan_cap, 1) AS so_nhan, count(*) AS so_dong
FROM danh_muc_chi_tiet ct
JOIN danh_muc dm ON dm.danh_muc_id = ct.danh_muc_id
WHERE array_length(ct.duong_dan, 1) > coalesce(array_length(dm.nhan_cap, 1), 0)
GROUP BY 1, 2, 3;

-- ---------------------------------------------------------------------------
-- Danh mục nào gồm những văn bản nào, kèm link nguồn và SỐ CÂU HỎI TEST đang
-- trỏ vào cùng văn bản đó. Đây là chỗ hai bộ dữ liệu gặp nhau.
--
-- Cố ý làm VIEW chứ không thêm cột `van_ban_id bigint[]` vào bảng `danh_muc`:
-- Postgres không kiểm được khóa ngoại trên từng phần tử mảng, nên cột đó vừa
-- không được bảo vệ vừa lặp lại thông tin đã có ở bảng chi tiết.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_danh_muc_van_ban AS
SELECT ct.ma_danh_muc,
       ct.van_ban,
       ct.van_ban_id,
       vb.ten  AS ten_van_ban,
       vb.link,
       count(*) FILTER (WHERE ct.loai_muc = 'muc') AS so_muc,
       count(*) AS so_dong,
       (SELECT count(DISTINCT cv.cau_hoi_id) FROM cau_hoi_van_ban cv
        WHERE cv.van_ban_id = ct.van_ban_id) AS so_cau_hoi_test
FROM v_danh_muc_chi_tiet ct
LEFT JOIN van_ban vb ON vb.van_ban_id = ct.van_ban_id
GROUP BY 1, 2, 3, 4, 5;

-- Kiểm tra chéo: có tên văn bản nào chưa tra ra được van_ban_id không.
-- Có dòng trả về là hoặc bảng `van_ban` thiếu văn bản đó, hoặc tên đang lưu
-- lệch so với `khoa` của nó.
CREATE OR REPLACE VIEW v_danh_muc_thieu_van_ban_id AS
SELECT dm.ma, ct.van_ban, count(*) AS so_dong
FROM danh_muc_chi_tiet ct
JOIN danh_muc dm ON dm.danh_muc_id = ct.danh_muc_id
WHERE ct.van_ban IS NOT NULL AND ct.van_ban_id IS NULL
GROUP BY 1, 2;

-- ---------------------------------------------------------------------------
-- Đếm cho đúng: mục thật vs các loại dòng khác. `count(*)` trên bảng chi tiết
-- nói quá số hóa chất, vì bản gốc trộn cả dòng nhóm / ghi chú / nối tiếp.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_danh_muc_dem AS
SELECT ma_danh_muc, van_ban, loai_muc, count(*) AS so_dong
FROM v_danh_muc_chi_tiet
GROUP BY 1, 2, 3;
